-- Add nutrition macro columns for user meal tracking
-- Run once in Supabase SQL editor

ALTER TABLE user_meals
ADD COLUMN IF NOT EXISTS protein DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS carbs DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS fat DOUBLE PRECISION;

ALTER TABLE user_food_records
ADD COLUMN IF NOT EXISTS protein DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS carbs DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS fat DOUBLE PRECISION;
